server:
  port: 38080

#指定注册中心地址
eureka:
  instance:
    hostname: 39.105.82.150
  client:
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/parkyy_service/


#服务的名称
spring:
  application:
    name: parkyy_service
